from collections.abc import Sequence
from typing import Protocol, runtime_checkable


@runtime_checkable
class ManagedServiceProtocol(Protocol):
    def install(self) -> bool: ...

    def uninstall(self, confirm: bool = False) -> bool: ...

    def is_installed(self) -> bool: ...

    def get_status(self) -> str: ...

    def get_info_lines(self) -> Sequence[str]: ...


@runtime_checkable
class ActivatableServiceProtocol(ManagedServiceProtocol, Protocol):
    def activate(self) -> bool: ...

    def deactivate(self, confirm: bool = False) -> bool: ...

    def is_active(self) -> bool: ...
